name: Build and Release Electron App

permissions:
  contents: write
  packages: write
  actions: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-package:
    uses: ./.github/workflows/build-and-package.yml
    secrets: inherit

  publish-release:
    needs: build-and-package
    runs-on: ubuntu-latest
    steps:
      - name: Download raux-setup.exe artifact
        uses: actions/download-artifact@v4
        with:
          name: raux-setup.exe
          path: ./release-artifacts

      - name: Download raux-setup.exe.sha256 artifact
        uses: actions/download-artifact@v4
        with:
          name: raux-setup.exe.sha256
          path: ./release-artifacts

      - name: Download raux-wheel-context artifact
        uses: actions/download-artifact@v4
        with:
          name: raux-wheel-context
          path: ./release-artifacts

      - name: Download gaiaui-ubuntu.deb artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: gaiaui-ubuntu.deb
          path: ./release-artifacts

      - name: Download gaiaui-ubuntu.deb.sha256 artifact
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: gaiaui-ubuntu.deb.sha256
          path: ./release-artifacts


      - name: Create GitHub Release and Upload Artifacts
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.build-and-package.outputs.production_version }}
          name: v${{ needs.build-and-package.outputs.production_version }}
          body: ${{ needs.build-and-package.outputs.changelog_notes }}
          files: |
            release-artifacts/raux-setup.exe
            release-artifacts/raux-setup.exe.sha256
            release-artifacts/raux-wheel-context.zip
            release-artifacts/*.deb
            release-artifacts/*.deb.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}