name: Build and package solution (pr)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build-and-package:
    uses: ./.github/workflows/build-and-package.yml
    secrets: inherit